### ISSUE TITLE
Hostname should be retrieved from postconf

### ISSUE THREAD

**Issue by Philippe23** [zoni/postforward#1]
Hostname should match the setting used by Postfix to remain consistent (and possibly to keep from leaking internal network information), so it should get the value from `/usr/sbin/postconf -h myhostname` instead of `os.Hostname()`.  (Although `os.Hostname()` seems a sane fallback if postconf fails for any reason.)

**Comment by zoni** [comment]
I just want to make a quick comment noting I pretty much agree with this, although there's a few details to work out. I intend to look at this more in-depth and incorporate something for this fairly soon.

**Comment by Philippe23** [comment]
No problem.  Feel free to ping me if you need input.

**Comment by zoni** [comment]
I've implemented this in v1.1.0, thanks for reporting this.
