### ISSUE TITLE
sendmail not found in $PATH

### ISSUE THREAD

**Issue by bynicolas** [zoni/postforward#2]
Hope you can guide me in the right direction here.

I keep getting this error.

`Error delivering message to sendmail: exec: "sendmail": executable file not found in $PATH`

I assume this is basic stuff, but sendmail is in $PATH as far as I know and I'm not sure what where to check next to make this work.  Is there a different user under which Postforward work?

**Comment by zoni** [comment]
Which OS are you running into this problem with? How is postfix installed? Package manager, or from source?

What is the value of your `$PATH` (try `echo $PATH` as the user postforward is invoked with, for starters) and what does `which sendmail` return?

**Comment by bynicolas** [comment]
I'm running ubuntu 16.04, Postfix is installed from package manager

As for the `$PATH` of the user postforward is invoked with, I'm not sure. Shouldn't it be `postfix`?

`which sendmail` returns `/usr/sbin/sendmail`

**Comment by zoni** [comment]
> As for the `$PATH` of the user postforward is invoked with, I'm not sure. Shouldn't it be `postfix`?

Typically yes, but it does depend on your postfix configuration and how you are calling postforward.

Can you give me the output of `postconf -p export_environment` please?

Can you also try adding that `export_environment` setting to your `main.cf`, but with `PATH` added to the list if it wasn't present yet?

If that also doesn't work, try setting PATH using `export_environment` explicitly and let me know if that helps. For example:

```
export_environment = TZ MAIL_CONFIG LANG PATH=/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by zoni** [comment]
(Your sendmail resides in `/usr/sbin/`. `/usr/sbin/` and `/sbin` are typically reserved for superuser commands, so it normally isn't on the `$PATH` for regular users, only root. This would explain why sendmail isn't being found in your situation)

**Comment by bynicolas** [comment]
Ok, so `postconf -p export_environment` returns `export_environment = TZ MAIL_CONFIG LANG` So I explicitly added PATH to it in `main.cf`

now `postconf -p export_environment` returns `export_environment = TZ MAIL_CONFIG LANG PATH=/usr/sbin:/usr/bin:/sbin:/bin` but still no go. I get the same error when postforward tries to send the rewritten header email.

Do you know how I can check how is postforward is being called. I mean from which user it is being run as?

**Comment by zoni** [comment]
Well that's a bummer. My mail system runs on FreeBSD, but I have access to Ubuntu 16.04 as well so I will attempt to reproduce your issue on that OS somewhere over the weekend.

> Do you know how I can check how is postforward is being called. I mean from which user it is being run as?

Turning on debug logging will likely include the information. Take a look at:

* http://www.postfix.org/postconf.5.html#debug_peer_list
* http://www.postfix.org/postconf.5.html#debug_peer_level

**Comment by bynicolas** [comment]
Can't seem to find more info on the user. Basically I have

```
Oct 13 17:48:56 mx postsrsd[17018]: srs_forward: <sender@example.com> rewritten as <SRS0=trMM=BM=example.com=sender@example.org>
Oct 13 17:48:56 mx postfix/local[17006]: 6A0394614A: to=<test_123@localhost.local>, orig_to=<recipient@example.net>, relay=local, delay=0.08, delays=0.05/0/0/0.02, dsn=4.3.0, status=deferred (temporary failure. Command output: Error delivering message to sendmail: exec: "sendmail": executable file not found in $PATH )
```

So to me it seems that postfix is calling `sendmail` but cannot find it!

Thanks for trying to debug this ;)

**Comment by zoni** [comment]
I've been able to reproduce this on my Ubuntu machine, which makes this a lot easier to investigate. :smile:.

From [LOCAL(8)](http://www.postfix.org/local.8.html):
> The **PATH**  environment  variable  is always reset to a system-dependent
> default path, and environment variables whose names are blessed by the
> `export_environment` configuration parameter are exported unchanged.

I was hoping this issue could be resolved with a simple postfix setting, but it appears pretty hard-coded on the postfix side. The easiest solution I see is to add another argument flag to postforward, allowing a user to supply a custom `$PATH` setting for it to use. I'll make this change somewhere over the coming week.

(As a temporary workaround, you could create a shell script which sets `$PATH` appropriately, then invokes postforward as usual. Instead of calling postforward from postfix directly, call this wrapper shell script. - don't forget to pipe stdin through appropriately.)

**Comment by zoni** [comment]
@bynicolas as of v1.1.0 you can now set `$PATH` appropriately for your system. Quoting the README:

> The postfix `local(8)` delivery agent uses a highly sanitized environment
for executed processes for security reasons. Depending on your operating
system, the default `$PATH` setting may be too strict for postforward to
locate the `sendmail` binary (Debian/Ubuntu are known to have this issue).
If this is the case for you, a custom `$PATH` may be set by supplying the
`--path` argument. For example: `--path /usr/sbin:/sbin:/usr/bin:/bin`

The example $PATH of `/usr/sbin:/sbin:/usr/bin:/bin` will do the trick on your system. Thanks for reporting this.
