### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by fisher006** [zoni/postforward#3]
I've added
forwarder: "|/usr/local/bin/postforward alias-name@domain.tld"

and commented sender_canonical_maps and leave only recipient_canonical

```
#sender_canonical_maps = hash:/etc/postfix/pfix-no-srs.cf, tcp:127.0.0.1:10001
#sender_canonical_classes = envelope_sender

recipient_canonical_maps = tcp:localhost:10002
recipient_canonical_classes= envelope_recipient,header_recipient
```

In main.cnf

alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases

and SRS doesn't work 

Can You help me with this issue? What logs You need to debug this

**Comment by zoni** [comment]
Just to rule out the obvious, did you run `newaliases` after updating `/etc/aliases`? That's needed to make changes to that file active.

If that is not the issue, all of the standard logs postfix generates when you send a message to the `forwarder` recipient would be a good place to start.

**Comment by zoni** [comment]
I'm closing this for now, please let me know if this is still an issue.
