### ISSUE TITLE
download source code from GH

### ISSUE THREAD

**Issue by wtps0n** [zoni/postforward#4]
Hello,

I'm trying add postforward to FreeBSD ports tree. But I cannot download source code from https://codeload.github.com. 

It should be such link (generated automatically by FreeBSD ports scripts):
https://codeload.github.com/zoni/postforward/tar.gz/1.1.0?dummy=/zoni-postforward-1.1.0_GH0.tar.gz

You can check donwload of postsrsd (link which works):
https://codeload.github.com/roehling/postsrsd/tar.gz/1.4?dummy=/roehling-postsrsd-1.4_GH0.tar.gz

Could you check of release procedure so standardized filename will be downloadable? I don't  how to do it - I'm not a developer.

Thanks a lot for your help

Greetings,

**Comment by zoni** [comment]
Hi there, and thanks for trying to get it into the FreeBSD ports tree!

I'm not sure how the FreeBSD script is generating that URL, but my guess is, there's an issue there. If you look at the releases page (https://github.com/zoni/postforward/releases) there's proper releases available. The `tar.gz` version of the latest release points to https://github.com/zoni/postforward/archive/v1.1.0.tar.gz for example, which redirects to https://codeload.github.com/zoni/postforward/tar.gz/v1.1.0.

I don't think there's anything more I could do on my end here.

**Comment by zoni** [comment]
Going to close this for now, but please let me know if there's any more action you would like me to take on my part.
